@baseUrl =  http://localhost:8081

# @name login
POST  {{baseUrl}}/login

{
  "username": "iron",
  "password": "123456"
}

###
GET {{baseUrl}}/dict?q=hello

### 
@authToken = {{login.response.body.$.data.token}}

# add one
POST {{baseUrl}}/records?type=2
x-token: {{authToken}}

{
  "text": "hello",
  "title": "hello world"
}

### add many
POST {{baseUrl}}/records?type=2
x-token: {{authToken}}

[
  {
    "text": "hello",
    "title": "hello world"
  },
  {
    "text": "world",
    "title": "hello world"
  }
]

### 
DELETE  {{baseUrl}}/records?type=2
x-token: {{authToken}}

{
  "text": ["hello","world"]
}

### 
GET   {{baseUrl}}/records?type=2
x-token: {{authToken}}
